# Generated by Django 3.1.7 on 2021-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default='2021-05-30 21:18:38'),
        ),
    ]
