# Generated by Django 3.1.4 on 2021-04-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20210405_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
