# Generated by Django 3.1.7 on 2021-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20210531_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Название'),
        ),
    ]
