# Generated by Django 3.1.4 on 2021-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_auto_20210407_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.CharField(max_length=40, null=True, verbose_name='Автор'),
        ),
    ]
