# Generated by Django 3.1.4 on 2021-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20210407_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
