# Generated by Django 3.1.4 on 2021-04-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_auto_20210407_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='place',
            field=models.CharField(max_length=80, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.CharField(max_length=30, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Товар'),
        ),
    ]
