# Generated by Django 3.1.7 on 2021-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_auto_20210531_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='Номер не указан', max_length=30, unique=True, verbose_name='Телефон'),
        ),
    ]
