# Generated by Django 3.1.7 on 2021-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_auto_20210415_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='slug',
            field=models.SlugField(default='default bb', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='default rubric', unique=True),
            preserve_default=False,
        ),
    ]
