# Generated by Django 3.1.7 on 2021-05-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_auto_20210415_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.CharField(default='Пользователь', max_length=30, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
